# Site settings
title: FISH Products Big Wall Climbing Gear
short_title: FISH Products
email: FishProductsInfo@gmail.com
description: "Absurdly good gear since 1983"
baseurl: "/fishproducts"
url: "http://www.fishproducts.com"
phone: "760.394.6665"
address: "FISH Products HC1 Box 696, Joshua Tree, CA. 92252"

# Build settings
markdown: kramdown
permalink: pretty
